name: 'Feed to Mastodon'
author: 'joschi'
description: 'Push ATOM/RSS feed updates to Mastodon via GitHub Actions'
branding:
  icon: 'rss'
  color: 'orange'
inputs:
  rss-feed:
    description: 'RSS feed URL'
    required: true
  status-visibility:
    description: 'Visibility of the posted status (public | unlisted | private | direct)'
    default: 'public'
  template:
    description: 'Template of status posted to Mastodon (Handlebars)'
    required: true
    default: '{{item.title}} {{item.link}}'
  dry-run:
    description: 'Only fetch RSS feed and update cache but skip posting to Mastodon.'
    default: 'false'
  sensitive:
    description: 'Mark Mastodon status as sensitive content.'
    default: 'false'
  cache-file:
    description: 'Cache file'
    required: true
  cache-limit:
    description: 'Cache limit'
    default: '100'
  api-endpoint:
    description: 'Mastodon API endpoint'
    required: true
  api-token:
    description: 'Mastodon access token'
    required: true
  initial-post-limit:
    description: 'The maximum number of posts created on the first run, if no cache file exists (default: unlimited)'
  post-limit:
    description: 'The maximum number of posts created per run (default: unlimited)'
runs:
  using: 'node20'
  main: 'dist/index.js'
