name: 'Feed to Mastodon'
author: 'selfagency'
description: 'Push ATOM/RSS feed updates to Mastodon via GitHub Actions'
branding:
  icon: 'rss'
  color: 'orange'
inputs:
  rss-feed:
    description: 'RSS feed URL'
    required: true
  status-visibility:
    description: 'Visibility of the posted status (public | unlisted | private | direct)'
    required: false
    default: 'public'
  dry-run:
    description: 'Only fetch RSS feed and update cache but skip posting to Mastodon.'
    required: false
    default: 'false'
  sensitive:
    description: 'Mark Mastodon status as sensitive content.'
    required: false
    default: 'false'
  cache-file:
    description: 'Cache file'
    required: true
  cache-limit:
    description: 'Cache limit'
    required: false
    default: '100'
  api-endpoint:
    description: 'Mastodon API endpoint'
    required: true
  api-token:
    description: 'Mastodon access token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
