name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24

      - name: Check package version
        id: check
        uses: 'EndBug/version-check@d17247dd94ca7b39d0b0691399be8d7c510622c9' # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Create release
        uses: 'ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd' # v1
        if: ${{ steps.check.outputs.changed == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.check.outputs.version}}
          name: v${{ steps.check.outputs.version}}
